#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
import re

g2 = None  # grib2io module reference, populated lazily by _ensure_dependencies()
np = None
# Standard meteorological convention for "useful" ACC forecast skill.
SKILL_THRESHOLD = 0.6

# Common GRIB2 file suffixes recognised when scanning input directories.
_GRIB2_SUFFIXES = frozenset({".grb2", ".grib2", ".grb", ".grib"})
_GRIB_MAGIC = b"GRIB"
_PROGRESS_EVERY = 25


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compute and plot 500 hPa geopotential height anomaly correlation "
            "coefficient (ACC) from GRIB2 files using grib2io."
        )
    )
    parser.add_argument("--analysis-dir", required=True, type=Path)
    parser.add_argument("--control-dir", required=True, type=Path)
    parser.add_argument("--experiment-dir", required=True, type=Path)
    parser.add_argument("--climo-dir", required=True, type=Path)
    parser.add_argument("--output-plot", required=True, type=Path)
    parser.add_argument("--max-lead", type=int, default=120)
    return parser.parse_args()


def _ensure_dependencies() -> None:
    global g2, np
    if g2 is None:
        try:
            import grib2io as _g2
        except ImportError as exc:
            raise ImportError("grib2io is required to read GRIB2 inputs.") from exc
        g2 = _g2
    if np is None:
        try:
            import numpy as _np
        except ImportError as exc:
            raise ImportError("numpy is required for ACC calculations.") from exc
        np = _np


def _select_hgt500(f) -> object:
    """Return the first 500 hPa geopotential height message from an open grib2io file object.

    Tries the wgrib2-style level string first ("500 mb"), then falls back to the raw
    GRIB2 type-of-fixed-surface / scaled-value approach (isobaric = 100, 50000 Pa).
    Returns None when no matching message is found.
    """
    # "500 mb" is the wgrib2-compatible level string generated by grib2io.
    msgs = f.select(shortName="HGT", level="500 mb")
    if msgs:
        return msgs[0]
    # Fallback: isobaric surface (typeOfFirstFixedSurface=100) at 50000 Pa.
    msgs = f.select(shortName="HGT", typeOfFirstFixedSurface=100,
                    valueOfFirstFixedSurface=50000.0)
    if msgs:
        return msgs[0]
    return None


def _open_grib2_file(path: Path) -> dict:
    """Open a GRIB2 file and return the 500 hPa HGT field together with timing metadata.

    Returns a dict with keys:
        valid_dt  – forecast valid time (datetime, UTC)
        ref_dt    – model initialisation (reference) time (datetime, UTC)
        hgt       – 2-D (ny × nx) numpy array of geopotential height values (gpm)
        lat       – 1-D latitude vector (degrees_north, south-to-north or north-to-south
                    depending on the file's scan order; matches the row dimension of hgt)
        lon       – 1-D longitude vector (degrees_east; matches the column dimension)
    """
    _ensure_dependencies()
    with g2.open(path) as f:
        msg = _select_hgt500(f)
        if msg is None:
            raise KeyError(
                f"Could not find a 500 hPa geopotential height message in {path}"
            )

        # grib2io exposes refDate and validDate as timezone-naive datetime objects;
        # attach UTC so that downstream arithmetic is unambiguous.
        ref_dt = msg.refDate.replace(tzinfo=timezone.utc)
        valid_dt = msg.validDate.replace(tzinfo=timezone.utc)

        hgt = np.array(msg.data, dtype=np.float64)

        # grid() returns 2-D (ny, nx) arrays.  For a regular lat/lon grid every row
        # has the same longitude and every column has the same latitude, so we can
        # safely collapse to 1-D by taking the first column (lat) and first row (lon).
        lats_2d, lons_2d = msg.grid()
        lat = np.array(lats_2d[:, 0], dtype=np.float64)
        lon = np.array(lons_2d[0, :], dtype=np.float64)

    return {"valid_dt": valid_dt, "ref_dt": ref_dt, "hgt": hgt, "lat": lat, "lon": lon}


def _acc_weighted(forecast_anom: np.ndarray, analysis_anom: np.ndarray, lat: np.ndarray) -> float:
    _ensure_dependencies()
    if lat.ndim != 1:
        raise ValueError("Latitude coordinate must be 1D for cosine-latitude ACC weighting.")

    # Apply sqrt(cos(lat)) weighting after removing spatial means.
    weights = np.sqrt(np.cos(np.deg2rad(lat)))[:, None]
    valid = np.isfinite(forecast_anom) & np.isfinite(analysis_anom)
    if not np.any(valid):
        return np.nan

    f = np.where(valid, forecast_anom, np.nan)
    a = np.where(valid, analysis_anom, np.nan)

    # Remove the spatial mean over valid points for each field.
    f_mean = float(np.nanmean(f))
    a_mean = float(np.nanmean(a))
    f = np.where(valid, f - f_mean, 0.0)
    a = np.where(valid, a - a_mean, 0.0)

    w = np.where(valid, weights, 0.0)
    f = w * f
    a = w * a

    numer = np.sum(f * a)
    denom = np.sqrt(np.sum(f * f) * np.sum(a * a))
    if np.isclose(denom, 0.0):
        return np.nan
    return float(numer / denom)


def _regrid(data: "np.ndarray", src_lat: "np.ndarray", src_lon: "np.ndarray",
            tgt_lat: "np.ndarray", tgt_lon: "np.ndarray") -> "np.ndarray":
    """Bilinear interpolation of a 2-D (lat x lon) field onto a target regular grid."""
    try:
        from scipy.interpolate import RegularGridInterpolator
    except ImportError as exc:
        raise ImportError(
            "scipy is required when the climatology grid differs from the forecast grid."
        ) from exc
    # RegularGridInterpolator requires strictly ascending coordinates.
    if src_lat[0] > src_lat[-1]:
        src_lat = src_lat[::-1]
        data = data[::-1, :]
    interp = RegularGridInterpolator(
        (src_lat, src_lon), data, method="linear", bounds_error=False, fill_value=None
    )
    tgt_lat_2d, tgt_lon_2d = np.meshgrid(tgt_lat, tgt_lon, indexing="ij")
    return interp((tgt_lat_2d, tgt_lon_2d))


def _load_climo(climo_dir: Path, mmdd: str, valid_hour: int,
               tgt_lat: "np.ndarray", tgt_lon: "np.ndarray") -> dict:
    _ensure_dependencies()
    # Search for a GRIB2 climo file using common naming conventions and extensions.
    candidates = [
        climo_dir / f"{stem}{suffix}"
        for stem in (f"hgt500_climo_{mmdd}", f"mean_{mmdd}")
        for suffix in (".grb2", ".grib2", ".grb", ".grib")
    ]
    path = next((c for c in candidates if c.exists()), None)
    if path is None:
        raise FileNotFoundError(
            f"Climatology GRIB2 file not found for MMDD={mmdd} in {climo_dir}"
        )

    with g2.open(path) as f:
        msgs = f.select(shortName="HGT", level="500 mb")
        if not msgs:
            msgs = f.select(shortName="HGT", typeOfFirstFixedSurface=100,
                            valueOfFirstFixedSurface=50000.0)
        if not msgs:
            raise KeyError(
                f"Could not find a 500 hPa geopotential height message in climatology file {path}"
            )

        # If the file contains several time slices (e.g., 00/06/12/18 Z means),
        # pick the message whose valid hour is closest to the requested valid_hour.
        if len(msgs) > 1:
            msg = min(msgs, key=lambda m: abs(m.validDate.hour - valid_hour))
        else:
            msg = msgs[0]

        hgt = np.array(msg.data, dtype=np.float64)
        lats_2d, lons_2d = msg.grid()
        src_lat = np.array(lats_2d[:, 0], dtype=np.float64)
        src_lon = np.array(lons_2d[0, :], dtype=np.float64)

    # Interpolate onto the forecast/analysis grid when resolutions differ.
    if src_lat.shape != tgt_lat.shape or src_lon.shape != tgt_lon.shape or not (
        np.allclose(src_lat, tgt_lat, atol=1e-6, rtol=1e-9)
        and np.allclose(src_lon, tgt_lon, atol=1e-6, rtol=1e-9)
    ):
        hgt = _regrid(hgt, src_lat, src_lon, tgt_lat, tgt_lon)

    return {"hgt": hgt, "lat": tgt_lat, "lon": tgt_lon}


def _looks_like_grib(path: Path) -> bool:
    try:
        with path.open("rb") as fh:
            return fh.read(len(_GRIB_MAGIC)) == _GRIB_MAGIC
    except OSError:
        return False


def _iter_grib2_files(directory: Path):
    for path in directory.rglob("*"):
        if path.is_file() and (
            path.suffix.lower() in _GRIB2_SUFFIXES or _looks_like_grib(path)
        ):
            yield path


def _format_dt(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %HZ")


def _describe_dates(valid_dates: set[datetime]) -> str:
    if not valid_dates:
        return "none"
    used_dates_sorted = sorted(valid_dates)
    return (
        f"{_format_dt(used_dates_sorted[0])} to "
        f"{_format_dt(used_dates_sorted[-1])} (n={len(used_dates_sorted)})"
    )


def _same_grid(a: dict, b: dict) -> bool:
    return np.allclose(a["lat"], b["lat"], atol=1e-6, rtol=1e-9) and np.allclose(
        a["lon"], b["lon"], atol=1e-6, rtol=1e-9
    )


def _mean_by_leads(acc_by_lead: dict, leads: list[int]) -> list[float]:
    return [float(np.nanmean(acc_by_lead[lead])) if lead in acc_by_lead else np.nan for lead in leads]


def _paired_diff_ci95(
    control_by_valid: dict,
    experiment_by_valid: dict,
) -> tuple[float, float, float]:
    """Return mean(exp-ctrl), lower95, upper95 from date-matched paired t interval."""
    try:
        from scipy.stats import t as student_t
    except ImportError as exc:
        raise ImportError("scipy is required to compute paired t confidence intervals.") from exc

    common_dates = sorted(set(control_by_valid.keys()) & set(experiment_by_valid.keys()))
    if not common_dates:
        return np.nan, np.nan, np.nan

    ctrl = np.array([control_by_valid[dt] for dt in common_dates], dtype=np.float64)
    exp = np.array([experiment_by_valid[dt] for dt in common_dates], dtype=np.float64)
    valid = np.isfinite(ctrl) & np.isfinite(exp)
    if not np.any(valid):
        return np.nan, np.nan, np.nan

    diff = exp[valid] - ctrl[valid]
    n = diff.size
    mean_diff = float(np.mean(diff))
    if n < 2:
        return mean_diff, mean_diff, mean_diff

    std = float(np.std(diff, ddof=1))
    stderr = std / np.sqrt(n)
    tcrit = float(student_t.ppf(0.975, df=n - 1))
    ci_half = tcrit * stderr
    return mean_diff, mean_diff - ci_half, mean_diff + ci_half


def main() -> None:
    args = parse_args()

    _ensure_dependencies()
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise ImportError("matplotlib is required to generate the ACC plot.") from exc

    print(f"Scanning experiment directory: {args.experiment_dir}")
    experiment_forecasts = []
    experiment_valid_dates = set()
    n_experiment_files = 0
    for path in _iter_grib2_files(args.experiment_dir):
        n_experiment_files += 1
        if n_experiment_files == 1 or n_experiment_files % _PROGRESS_EVERY == 0:
            print(f"  Experiment scan: inspected {n_experiment_files} files...")
        fcst = _open_grib2_file(path)
        lead = int(round((fcst["valid_dt"] - fcst["ref_dt"]).total_seconds() / 3600.0))
        if lead < 0 or lead > args.max_lead:
            continue
        experiment_forecasts.append((path, fcst))
        experiment_valid_dates.add(fcst["valid_dt"])
    if n_experiment_files == 0:
        raise ValueError(
            "Experiment directory must contain GRIB2 files "
            f"({', '.join(sorted(_GRIB2_SUFFIXES))})."
        )
    if not experiment_forecasts:
        raise ValueError(
            f"No experiment forecast files within 0-{args.max_lead}h lead were found."
        )
    print(
        "Experiment scan complete: "
        f"{len(experiment_forecasts)} usable files covering "
        f"{_describe_dates(experiment_valid_dates)}."
    )

    analysis_by_valid = {}
    n_analysis_f00 = 0
    print(
        f"Scanning analysis directory: {args.analysis_dir} "
        f"for {len(experiment_valid_dates)} experiment valid dates"
    )
    n_analysis_files = 0
    for path in _iter_grib2_files(args.analysis_dir):
        n_analysis_files += 1
        if n_analysis_files == 1 or n_analysis_files % _PROGRESS_EVERY == 0:
            print(f"  Analysis scan: inspected {n_analysis_files} files...")
        info = _open_grib2_file(path)
        # Enforce analysis inputs to be f00 only (lead == 0).
        lead = int(round((info["valid_dt"] - info["ref_dt"]).total_seconds() / 3600.0))
        if lead != 0:
            continue
        analysis_by_valid[info["valid_dt"]] = info
        n_analysis_f00 += 1
        if info["valid_dt"] in experiment_valid_dates:
            print(
                "  Matched analysis valid time "
                f"{_format_dt(info['valid_dt'])} "
                f"({len(set(analysis_by_valid) & experiment_valid_dates)}/"
                f"{len(experiment_valid_dates)})"
            )
            if experiment_valid_dates.issubset(analysis_by_valid):
                print("  Found all experiment dates in analysis directory; stopping early.")
                break

    if n_analysis_f00 == 0:
        raise ValueError(
            "No f00 analysis files found in analysis-dir. "
            "Provide analysis files with lead 0 only."
        )
    matched_analysis_dates = set(analysis_by_valid) & experiment_valid_dates
    print(
        "Analysis scan complete: "
        f"matched {len(matched_analysis_dates)} of {len(experiment_valid_dates)} "
        f"experiment valid dates after inspecting {n_analysis_files} files."
    )

    cached_climo = {}
    control_acc_by_lead = defaultdict(list)
    experiment_acc_by_lead = defaultdict(list)
    control_acc_by_lead_valid = defaultdict(dict)
    experiment_acc_by_lead_valid = defaultdict(dict)
    used_valid_dates = set()

    def process_forecast(path: Path, fcst: dict, target: defaultdict, target_by_valid: defaultdict) -> bool:
        lead = int(round((fcst["valid_dt"] - fcst["ref_dt"]).total_seconds() / 3600.0))
        if lead < 0 or lead > args.max_lead:
            return False

        if fcst["valid_dt"] not in analysis_by_valid:
            return False

        analysis = analysis_by_valid[fcst["valid_dt"]]
        if not _same_grid(fcst, analysis):
            raise ValueError(f"Grid mismatch between forecast and analysis for {path}")

        mmdd = fcst["valid_dt"].strftime("%m%d")
        valid_hour = fcst["valid_dt"].hour
        climo_key = (mmdd, valid_hour)
        if climo_key not in cached_climo:
            cached_climo[climo_key] = _load_climo(
                args.climo_dir, mmdd, valid_hour, fcst["lat"], fcst["lon"]
            )
        climo = cached_climo[climo_key]

        fcst_anom = fcst["hgt"] - climo["hgt"]
        anly_anom = analysis["hgt"] - climo["hgt"]
        acc_value = _acc_weighted(fcst_anom, anly_anom, fcst["lat"])
        target[lead].append(acc_value)
        target_by_valid[lead][fcst["valid_dt"]] = acc_value
        used_valid_dates.add(fcst["valid_dt"])
        return True

    print(f"Scanning control directory: {args.control_dir}")
    n_control_files = 0
    n_control_matches = 0
    for path in _iter_grib2_files(args.control_dir):
        n_control_files += 1
        if n_control_files == 1 or n_control_files % _PROGRESS_EVERY == 0:
            print(f"  Control scan: inspected {n_control_files} files...")
        fcst = _open_grib2_file(path)
        if process_forecast(path, fcst, control_acc_by_lead, control_acc_by_lead_valid):
            n_control_matches += 1
    if n_control_files == 0:
        raise ValueError(
            "Control directory must contain GRIB2 files "
            f"({', '.join(sorted(_GRIB2_SUFFIXES))})."
        )
    print(
        "Control scan complete: "
        f"matched {n_control_matches} files after inspecting {n_control_files} files."
    )

    print(f"Processing {len(experiment_forecasts)} experiment forecast files...")
    n_experiment_matches = 0
    for idx, (path, fcst) in enumerate(experiment_forecasts, start=1):
        if idx == 1 or idx % _PROGRESS_EVERY == 0:
            print(f"  Experiment processing: inspected {idx} files...")
        if process_forecast(path, fcst, experiment_acc_by_lead, experiment_acc_by_lead_valid):
            n_experiment_matches += 1
    print(
        "Experiment processing complete: "
        f"matched {n_experiment_matches} files."
    )

    leads = sorted(set(control_acc_by_lead.keys()) | set(experiment_acc_by_lead.keys()))
    if not leads:
        raise ValueError("No matched valid times were found to compute ACC.")

    control_acc = _mean_by_leads(control_acc_by_lead, leads)
    experiment_acc = _mean_by_leads(experiment_acc_by_lead, leads)

    diff_mean = []
    diff_low = []
    diff_high = []
    for lead in leads:
        mean_diff, low95, high95 = _paired_diff_ci95(
            control_acc_by_lead_valid.get(lead, {}),
            experiment_acc_by_lead_valid.get(lead, {}),
        )
        diff_mean.append(mean_diff)
        diff_low.append(low95)
        diff_high.append(high95)

    used_dates_sorted = sorted(used_valid_dates)
    if used_dates_sorted:
        start_dt = _format_dt(used_dates_sorted[0])
        end_dt = _format_dt(used_dates_sorted[-1])
        dates_text = f"Dates used: {start_dt} to {end_dt} (n={len(used_dates_sorted)})"
    else:
        dates_text = "Dates used: none"

    fig, (ax_abs, ax_diff) = plt.subplots(
        2, 1, figsize=(10, 8), sharex=True, gridspec_kw={"height_ratios": [3, 2]}
    )

    ax_abs.plot(leads, control_acc, marker="o", linestyle="-", label="Control Run")
    ax_abs.plot(leads, experiment_acc, marker="s", linestyle="--", label="Experiment")
    ax_abs.axhline(
        SKILL_THRESHOLD,
        color="gray",
        linestyle=":",
        linewidth=1.0,
        label=f"Skill Threshold ({SKILL_THRESHOLD:.1f})",
    )
    x_ticks = [0, 24, 48, 72, 96, 120, 144, 168, 192]
    ax_abs.set_ylim(0.6, 1.0)
    ax_abs.set_xlim(0, 192)
    ax_abs.set_xticks(x_ticks)
    ax_abs.set_ylabel("ACC")
    ax_abs.set_title(f"500 hPa Geopotential Height ACC\n{dates_text}")
    ax_abs.grid(True, linestyle="--", alpha=0.4)
    ax_abs.legend()

    ci_low_arr = np.array(diff_low, dtype=np.float64)
    ci_high_arr = np.array(diff_high, dtype=np.float64)
    ci_half = 0.5 * (ci_high_arr - ci_low_arr)
    ax_diff.bar(
        leads,
        2.0 * ci_half,
        bottom=-ci_half,
        width=8,
        color="tab:orange",
        alpha=0.25,
        edgecolor="tab:orange",
        linewidth=0.8,
        label="95% CI (centered on 0)",
    )
    ax_diff.plot(leads, diff_mean, marker="d", linestyle="-", color="tab:red", label="Exp - Ctrl")
    ax_diff.axhline(0.0, color="k", linewidth=0.8)
    ax_diff.set_xticks(x_ticks)
    ax_diff.set_xlabel("Lead time (hours)")
    ax_diff.set_ylabel("ACC Difference")
    ax_diff.grid(True, linestyle="--", alpha=0.4)
    ax_diff.set_ylim(-0.02, 0.025)
    ax_diff.legend()

    fig.tight_layout()

    args.output_plot.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.output_plot, dpi=150)
    print(f"Saved plot to {args.output_plot}")

    target_lead = 120
    control_ts_map = control_acc_by_lead_valid.get(target_lead, {})
    experiment_ts_map = experiment_acc_by_lead_valid.get(target_lead, {})
    common_valid_dates = sorted(set(control_ts_map.keys()) & set(experiment_ts_map.keys()))

    if common_valid_dates:
        control_ts = [control_ts_map[dt] for dt in common_valid_dates]
        experiment_ts = [experiment_ts_map[dt] for dt in common_valid_dates]
        diff_ts = [exp - ctrl for ctrl, exp in zip(control_ts, experiment_ts)]

        ts_start = _format_dt(common_valid_dates[0])
        ts_end = _format_dt(common_valid_dates[-1])
        ts_dates_text = f"Dates used: {ts_start} to {ts_end} (n={len(common_valid_dates)})"

        fig_ts, (ax_ts_abs, ax_ts_diff) = plt.subplots(
            2, 1, figsize=(11, 8), sharex=True, gridspec_kw={"height_ratios": [3, 2]}
        )

        ax_ts_abs.plot(common_valid_dates, control_ts, marker="o", linestyle="-", label="Control Run")
        ax_ts_abs.plot(common_valid_dates, experiment_ts, marker="s", linestyle="--", label="Experiment")
        ax_ts_abs.axhline(
            SKILL_THRESHOLD,
            color="gray",
            linestyle=":",
            linewidth=1.0,
            label=f"Skill Threshold ({SKILL_THRESHOLD:.1f})",
        )
        ax_ts_abs.set_ylim(0.5, 1.0)
        ax_ts_abs.set_ylabel("ACC")
        ax_ts_abs.set_title(f"500 hPa ACC Time Series at {target_lead}h Lead\n{ts_dates_text}")
        ax_ts_abs.grid(True, linestyle="--", alpha=0.4)
        ax_ts_abs.legend()

        ax_ts_diff.plot(common_valid_dates, diff_ts, marker="d", linestyle="-", color="tab:red", label="Exp - Ctrl")
        ax_ts_diff.axhline(0.0, color="k", linewidth=0.8)
        ax_ts_diff.set_xlabel("Valid time (UTC)")
        ax_ts_diff.set_ylabel("ACC Difference")
        ax_ts_diff.grid(True, linestyle="--", alpha=0.4)
        ax_ts_diff.legend()

        fig_ts.autofmt_xdate(rotation=30)
        fig_ts.tight_layout()

        ts_plot = args.output_plot.with_name(
            f"{args.output_plot.stem}_timeseries_f{target_lead:03d}{args.output_plot.suffix}"
        )
        fig_ts.savefig(ts_plot, dpi=150)
        print(f"Saved plot to {ts_plot}")
    else:
        print(f"No matched control/experiment dates found for {target_lead}h time-series plot.")


if __name__ == "__main__":
    main()
